{% set version = "0.3.3" %}

# explicitly pin openblas to avoid issue of potential mismatch as seen in gh-8

package:
  name: scikit-umfpack
  version: {{ version }}

source:
  git_url: https://github.com/michaelweinold/scikit-umfpack
  git_tag: {{ version }}
  # compare: https://stackoverflow.com/a/22565201

build:
  skip: True  # [win]
  number: 1004
  features:

requirements:
  build:
    - {{ compiler('c') }}
    - swig
  host:
    - libblas
    - libcblas
    - python
    - numpy
    - scipy
    - suitesparse
    - setuptools
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - suitesparse
    - setuptools

test:
  requires:
    - nose
  imports:
    - scikits.umfpack

about:
  home: https://scikit-umfpack.github.io/scikit-umfpack
  license: GPL-2.0
  license_file: LICENSE
  summary: The umfpack scikit provides a wrapper of the UMFPACK sparse direct solver to SciPy.

extra:
    recipe-maintainers:
      - grlee77
      - cmutel
