{% set version = "0.2.3" %}

# explicitly pin openblas to avoid issue of potential mismatch as seen in gh-8
{% set variant = "openblas" %}

package:
  name: scikit-umfpack
  version: {{ version }}

source:
  fn: scikit-umfpack--{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/source/s/scikit-umfpack/scikit-umfpack-{{ version }}.tar.gz
  sha256: 9c8935717b17e8b43ad8ec989c2ca0e48c1e1b01fe0d1a16e19feecde2ee9524

build:
  skip: True  # [win]
  number: 200
  features:
    - blas_{{ variant }}

requirements:
  build:
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*
    - python
    - numpy x.x
    - scipy
    - suitesparse
    - swig
    - setuptools
  run:
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*
    - python
    - numpy x.x
    - scipy
    - suitesparse
    - setuptools

test:
  requires:
    - nose
  imports:
    - scikits.umfpack

about:
  home: https://scikit-umfpack.github.io/scikit-umfpack
  license: GPL 2
  summary: The umfpack scikit provides a wrapper of the UMFPACK sparse direct solver to SciPy.

extra:
    recipe-maintainers:
      - grlee77
      - cmutel
