{% set name = "scikit-umfpack" %}
{% set version = "0.4.2" %}

# explicitly pin openblas to avoid issue of potential mismatch as seen in gh-8

package:
  name: scikit-umfpack
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7cd652e6559804a52379f4ff367cfad54d6f7a6fc65a5e0bd26d26a1282c3f64
  patches:
    - strict-compiler.patch

build:
  number: 1
  features:
  script:
    - CFLAGS="CFLAGS -I$PREFIX/include -I/$PREFIX/include/suitesparse" LDFLAGS="$LDFLAGS -L$PREFIX/lib" {{ PYTHON }} -m pip install . --no-build-isolation -vvv -Csetup-args=${MESON_ARGS// / -Csetup-args=}  # [build_platform != target_platform]
    - {{ PYTHON }} -m pip install . --no-deps -vvv -Csetup-args=${MESON_ARGS// / -Csetup-args=}  # [unix]
    - {{ PYTHON }} -m pip install . --no-deps -vvv                                               # [win]
  run_exports:
    - {{ pin_subpackage('scikit-umfpack', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - meson-python                           # [build_platform != target_platform]
    - suitesparse                              # [build_platform != target_platform]
    - pkg-config
    - swig
  host:
    - libblas
    - libcblas
    - python
    - numpy
    - scipy
    - suitesparse
    - setuptools
    - meson-python
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - suitesparse
    - setuptools

test:
  requires:
    - pytest
    - numpy
    - scipy
    - pip
  source_files:
    - scikits/umfpack/tests
  commands:
    - python -m pip check
    - python -m pytest scikits/umfpack/tests

about:
  home: https://scikit-umfpack.github.io/scikit-umfpack
  license: BSD-3-Clause
  license_file: LICENSE
  summary: The umfpack scikit provides a wrapper of the UMFPACK sparse direct solver to SciPy.

extra:
    recipe-maintainers:
      - grlee77
      - cmutel
      - michaelweinold
      - JarrettSJohnson
      - rfiorella
