{% set version = "0.3.2" %}

# explicitly pin openblas to avoid issue of potential mismatch as seen in gh-8
{% set variant = "openblas" %}

package:
  name: scikit-umfpack
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/s/scikit-umfpack/scikit-umfpack-{{ version }}.tar.gz
  sha256: 9ca57adf461a60ef96871c6228f218ef233acc5b0ca147788979a683d3440117

build:
  skip: True  # [win]
  number: 1000
  features:
    - blas_{{ variant }}

requirements:
  host:
    - blas 1.1 {{ variant }}
    - openblas
    - python
    - numpy
    - scipy
    - suitesparse
    - swig
    - setuptools
  run:
    - blas 1.1 {{ variant }}
    - openblas
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - suitesparse
    - setuptools

test:
  requires:
    - nose
  imports:
    - scikits.umfpack

about:
  home: https://scikit-umfpack.github.io/scikit-umfpack
  license: GPL-2.0
  summary: The umfpack scikit provides a wrapper of the UMFPACK sparse direct solver to SciPy.

extra:
    recipe-maintainers:
      - grlee77
      - cmutel
