{% set version = "0.3.1" %}

# explicitly pin openblas to avoid issue of potential mismatch as seen in gh-8
{% set variant = "openblas" %}

package:
  name: scikit-umfpack
  version: {{ version }}

source:
  fn: scikit-umfpack--{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/source/s/scikit-umfpack/scikit-umfpack-{{ version }}.tar.gz
  sha256: 6236856ed34a74a541028a80989372e956ccfbd2751de0ee74b7e0800f50f3b7

build:
  skip: True  # [win]
  number: 0
  features:
    - blas_{{ variant }}

requirements:
  build:
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*
    - python
    - numpy 1.11.*
    - scipy
    - suitesparse
    - swig
    - setuptools
  run:
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*
    - python
    - numpy >=1.11
    - scipy
    - suitesparse
    - setuptools

test:
  requires:
    - nose
  imports:
    - scikits.umfpack

about:
  home: https://scikit-umfpack.github.io/scikit-umfpack
  license: GPL 2
  summary: The umfpack scikit provides a wrapper of the UMFPACK sparse direct solver to SciPy.

extra:
    recipe-maintainers:
      - grlee77
      - cmutel
