travis:
  secure:
    BINSTAR_TOKEN: GwpNHH6JhB84wMQdXuX1V2T6bUbZVk0y4ZS00kJVZPX8qi61Mxco4QQ/ukxmSiMn2SoQh+o3UX4LGdmwreows5otB3HMll4q65P27a1vCEIo/Byi0HRTxSFZ1bYL4tPlxs5rkLbReUL7DenBuB1YswJWjbPJemsbbJ6IiBVohbr43WP3nJDo6U/Wx9zkysZjFj0kh6mZJ1dmxPPk0Gqkykueyh88hiy2zMcot4Zk21l2sjUc5dmndxdKnM9GBPKUJGKg5/LM0Rv4dru9Usc+GGnv/3LShiqPpeVYcsgyOvxXP7RUUfEx5O7C75eSuuVH2P/5bcSYGQ2sfg3Jb6GwSWVML7PknoTpuDY64KzBkxmAbqotW/sSTyTtHJbqSp2Orm1q6oO7IKpw/ADU4yGaml5JyGBSj+n+g40NyrQeZFXS8FaVUOJl6Q/Zh55FBzRlAKtIIY7sWXBeSjzzwQ6g1kjT0Wi7pAJU1NOOGz/tLVZGNFKD6JzEulrG4WfwLz12b7/O0CV7HcfI6ney34rnJxazR5s/0/c6ppU/rmFOaztC3TPbi6/0qf2Ku1DmCjtGotSaoeup6ilx3kfEhQcGYMthn0gI0wW3GFSAZGNNRSI/pwemrGOvau15cqGpl8BpdL7EmHUVkvgeS2iORO0ZikHQJaa14rvCu9ccAgWF3Y8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
