appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: GMQ5M1FAIBd/Lwr+4IVSfbAW6quvvpPmoGilJ2kjLjEuqx5YuzujX0TD2xlO3HOf2dKbQyqh6srAaLBKy0cIziyjdo65SOI5syvpU0CZ4paTXbLCy7I1CqVcvo6vpe6KfasDb7oxwFDQS/7b3YUIiBn9PXcXzBjGv1pGrSwUVplpvJ7HAus3fNpiTpOznW/AK1tJN/4EEwooX/YfV9yeTkjCMxoUIt2WyekhI1MFRyi5O+uwPGaVywbXu80UrFL7xCHoobaS3/dMrwQkdZe+aTSUBdhkiIRVC8n+sJfdY/eCuaTKFV0fGvmU57eUn4Sic5iObV7lePssrVekze0HUlMvWXlrTuDCRqEPnkBIAKtf6x1s5U40nE8KPVaHTYbjN/LUYxYqMPzQkoDuEHiRyqyFRdED6xGte7RA3zMYThf5agERtSpMtrl/mF44LFx+CvY1YtulHj2z4bT03IFZdYDniqJjy4DcFM4sQ0bOBUcE4BbV+wM2rRiKcRstda3jCfx0AB1gDxDQZvMNvKSh7FppTdGdSA0rvBEpJyRTswoHHQxYk9u99hCcbdhR4ccyWUh6M6PoUC7Miw9H8GsRgEg3G3Ek5Rteuu2tb0WOoelhSrdRxF/1Q41sWvZyHIvC9a1wf1dkX8rxlRc/wBY0MAX+WZucp1wWM1eN6P6jYxY=}
